### ISSUE TITLE
Error on installing yarn

### ISSUE THREAD

**Issue by sbenthall** [yrevocnu/psychedelic-glass-bead-game#1]
Following README instructions as best I can, I got this error:

```
$ yarn install
yarn install v1.21.1
[1/5] Validating package.json...
error mousse-truffee@1.0.0: The engine "node" is incompatible with this module. Expected version "13.12.0". Got "13.13.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by benheller** [comment]
This is due to the `.nvmrc` in our project's root that requires a particular node version. You can type `nvm install` in the project root to install the correct version of node. In the future, you can type `nvm use` to select that version, if you've been working on another project that uses a different node version.

If you want to update the project to use `13.13.0` you can change this in `.nvmrc` and `package.json`

**Comment by sbenthall** [comment]
that works thanks
