### ISSUE TITLE
eslint finding almost a thousand issues with bundle.js

### ISSUE THREAD

**Issue by sbenthall** [yrevocnu/psychedelic-glass-bead-game#42]
https://gist.github.com/sbenthall/ee2e3dd6c236aa25a0b01fe4e7574732

**Comment by benheller** [comment]
@sbenthall the `/web` directory does not exist in this repository. Please perform a clean checkout of the code and you will have no linting errors.

**Comment by sbenthall** [comment]
that is interesting.

Do you know what in the running of the code would create a web/ directory?
Would it be possible to include an ignore command, analogous to a .gitignore, that would prevent the linter from looking at this directory?

**Comment by benheller** [comment]
The code no longer creates that directory--it should be deleted from your local copy. It's a remnant from when this repository used to contain both server and web code, but all the web code has since been removed. Directories and files that aren't "tracked" in `git` will remain on your local host. Since these are generated files, they wouldn't have been removed when the code that generated them was deleted from the repo. It's up to the user to delete these generated directories manually or perform a fresh checkout of the repository code.

It's not the right solve here, but if you had a valid case where you wished to lint some directories and not others, you could use a `.eslintignore`: https://eslint.org/docs/user-guide/configuring#ignorepatterns-in-config-files

**Comment by sbenthall** [comment]
OK, that all makes sense.
Thanks for letting me know that the files are no longer generated.
